### ISSUE TITLE
Instance annotation

### ISSUE THREAD

**Issue by thuyen** [cocodataset/panopticapi#5]
I am trying to visualize some annotations output from instance_data.py. In the following are three images of class `PERSON` (in the validation set), each shows the mask of `ONE` particular instance of class `PERSON` (the foreground are `WHITE`). Are they supposed to be like this?

000000364884.jpg
![000000364884_person](https://user-images.githubusercontent.com/4015328/43178913-bbdd39ac-8f84-11e8-8bb4-18ab3e525242.png)
000000005586.jpg
![000000005586_person](https://user-images.githubusercontent.com/4015328/43178897-a3cf958a-8f84-11e8-8f02-05b1058257f4.png)
000000191845.jpg
![000000191845_person](https://user-images.githubusercontent.com/4015328/43178939-dd7e4ae2-8f84-11e8-816e-36b0ec974fdd.png)

**Comment by alexander-kirillov** [comment]
Everything is correct here. These are examples of special kind of annotations called "crowd regions". The annotations has field 'iscrowd' set to 1. They represent groups of objects (that are usually hard to split) rather than a single instance. You can find more information about the crowd regions in [COCO data format page](http://cocodataset.org/#format-data). Note that original COCO data for instance segmentation has the same regions as well.

**Comment by thuyen** [comment]
Got it. Thanks. The annotations still look very weird though, especially 000000005586.png. 

Another question: I insert `assert semantic.min() > 0`  at [line 34](https://github.com/cocodataset/panopticapi/blob/master/semantic_data.py#L34) on `semantic_data.py` and the scripts fails from the start. So not all pixels are annotated?

**Comment by alexander-kirillov** [comment]
You are right. Some pixels do not have labels at all. They were not annotated or they belong to the stuff categories that we are ignoring. Please see [coco panoptic evaluation](http://cocodataset.org/#panoptic-eval) (click on "merged or ignored") for more details about ignored categories.

**Comment by thuyen** [comment]
Got it. Thanks!
